// Package identityclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package identityclient

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: //schemas/ErrorModel.json
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	//
	// Examples: Property foo is required but is missing.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	//
	// Examples: https://example.com/error-log/abc123
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	//
	// Examples: 400
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	//
	// Examples: Bad Request
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	//
	// Examples: https://example.com/errors/example
	Type *string `json:"type,omitempty"`
}

// HealthOutBody defines model for HealthOutBody.
type HealthOutBody struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: //schemas/HealthOutBody.json
	Schema *string `json:"$schema,omitempty"`

	// Status Examples: ok
	Status string `json:"status"`
}

// ReadyOutBody defines model for ReadyOutBody.
type ReadyOutBody struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: //schemas/ReadyOutBody.json
	Schema *string `json:"$schema,omitempty"`

	// Status Examples: ready
	Status string `json:"status"`
}

// StartOutBody defines model for StartOutBody.
type StartOutBody struct {
	// Schema A URL to the JSON Schema for this object.
	//
	// Examples: //schemas/StartOutBody.json
	Schema *string `json:"$schema,omitempty"`

	// Status Examples: started
	Status string `json:"status"`
}

// BrokerCallbackParams defines parameters for BrokerCallback.
type BrokerCallbackParams struct {
	// Token Single-use callback artifact
	Token *string `form:"token,omitempty" json:"token,omitempty"`

	// SsoToken Single-use SSO callback artifact
	SsoToken *string `form:"sso_token,omitempty" json:"sso_token,omitempty"`
	Type     *string `form:"type,omitempty" json:"type,omitempty"`
}

// BrokerLoginParams defines parameters for BrokerLogin.
type BrokerLoginParams struct {
	Accept                               *string `json:"Accept,omitempty"`
	UnderscoreUnderscoreHostPrimerBroker *string `form:"__Host-primer-broker,omitempty" json:"__Host-primer-broker,omitempty"`
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// BrokerCallback Complete a broker callback
	//
	// Corresponds with GET /broker/stytch/callback (the `BrokerCallback` operationId).
	BrokerCallback(ctx context.Context, params *BrokerCallbackParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BrokerEmailStart Start a broker authentication method
	//
	// Corresponds with POST /broker/stytch/email/start (the `BrokerEmailStart` operationId).
	BrokerEmailStart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BrokerEmailVerify Start a broker authentication method
	//
	// Corresponds with POST /broker/stytch/email/verify (the `BrokerEmailVerify` operationId).
	BrokerEmailVerify(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BrokerLogin Broker login discovery
	//
	// Corresponds with GET /broker/stytch/login (the `BrokerLogin` operationId).
	BrokerLogin(ctx context.Context, params *BrokerLoginParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BrokerSSOStart Start a broker authentication method
	//
	// Corresponds with POST /broker/stytch/sso/start (the `BrokerSSOStart` operationId).
	BrokerSSOStart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Healthz Liveness probe
	//
	// Corresponds with GET /healthz (the `Healthz` operationId).
	Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OauthAuthorize Start an OAuth authorization request
	//
	// Corresponds with GET /oauth/authorize (the `OauthAuthorize` operationId).
	OauthAuthorize(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Readyz Readiness probe (database ping)
	//
	// Corresponds with GET /readyz (the `Readyz` operationId).
	Readyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// BrokerCallback Complete a broker callback
//
// Corresponds with GET /broker/stytch/callback (the `BrokerCallback` operationId).
func (c *Client) BrokerCallback(ctx context.Context, params *BrokerCallbackParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBrokerCallbackRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// BrokerEmailStart Start a broker authentication method
//
// Corresponds with POST /broker/stytch/email/start (the `BrokerEmailStart` operationId).
func (c *Client) BrokerEmailStart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBrokerEmailStartRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// BrokerEmailVerify Start a broker authentication method
//
// Corresponds with POST /broker/stytch/email/verify (the `BrokerEmailVerify` operationId).
func (c *Client) BrokerEmailVerify(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBrokerEmailVerifyRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// BrokerLogin Broker login discovery
//
// Corresponds with GET /broker/stytch/login (the `BrokerLogin` operationId).
func (c *Client) BrokerLogin(ctx context.Context, params *BrokerLoginParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBrokerLoginRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// BrokerSSOStart Start a broker authentication method
//
// Corresponds with POST /broker/stytch/sso/start (the `BrokerSSOStart` operationId).
func (c *Client) BrokerSSOStart(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBrokerSSOStartRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// Healthz Liveness probe
//
// Corresponds with GET /healthz (the `Healthz` operationId).
func (c *Client) Healthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// OauthAuthorize Start an OAuth authorization request
//
// Corresponds with GET /oauth/authorize (the `OauthAuthorize` operationId).
func (c *Client) OauthAuthorize(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOauthAuthorizeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// Readyz Readiness probe (database ping)
//
// Corresponds with GET /readyz (the `Readyz` operationId).
func (c *Client) Readyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReadyzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewBrokerCallbackRequest constructs an http.Request for the BrokerCallback method
func NewBrokerCallbackRequest(server string, params *BrokerCallbackParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/broker/stytch/callback")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Token != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "token", *params.Token, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SsoToken != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "sso_token", *params.SsoToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Type != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", false, "type", *params.Type, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBrokerEmailStartRequest constructs an http.Request for the BrokerEmailStart method
func NewBrokerEmailStartRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/broker/stytch/email/start")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBrokerEmailVerifyRequest constructs an http.Request for the BrokerEmailVerify method
func NewBrokerEmailVerifyRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/broker/stytch/email/verify")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBrokerLoginRequest constructs an http.Request for the BrokerLogin method
func NewBrokerLoginRequest(server string, params *BrokerLoginParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/broker/stytch/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.Accept != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Accept", *params.Accept, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Accept", headerParam0)
		}

	}

	if params != nil {

		if params.UnderscoreUnderscoreHostPrimerBroker != nil {
			var cookieParam0 string

			cookieParam0, err = runtime.StyleParamWithOptions("simple", true, "__Host-primer-broker", *params.UnderscoreUnderscoreHostPrimerBroker, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationCookie, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			cookie0 := &http.Cookie{
				Name:  "__Host-primer-broker",
				Value: cookieParam0,
			}
			req.AddCookie(cookie0)
		}
	}
	return req, nil
}

// NewBrokerSSOStartRequest constructs an http.Request for the BrokerSSOStart method
func NewBrokerSSOStartRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/broker/stytch/sso/start")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHealthzRequest constructs an http.Request for the Healthz method
func NewHealthzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOauthAuthorizeRequest constructs an http.Request for the OauthAuthorize method
func NewOauthAuthorizeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/oauth/authorize")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReadyzRequest constructs an http.Request for the Readyz method
func NewReadyzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// BrokerCallbackWithResponse Complete a broker callback
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /broker/stytch/callback (the `BrokerCallback` operationId).
	BrokerCallbackWithResponse(ctx context.Context, params *BrokerCallbackParams, reqEditors ...RequestEditorFn) (*BrokerCallbackResponse, error)

	// BrokerEmailStartWithResponse Start a broker authentication method
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /broker/stytch/email/start (the `BrokerEmailStart` operationId).
	BrokerEmailStartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*BrokerEmailStartResponse, error)

	// BrokerEmailVerifyWithResponse Start a broker authentication method
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /broker/stytch/email/verify (the `BrokerEmailVerify` operationId).
	BrokerEmailVerifyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*BrokerEmailVerifyResponse, error)

	// BrokerLoginWithResponse Broker login discovery
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /broker/stytch/login (the `BrokerLogin` operationId).
	BrokerLoginWithResponse(ctx context.Context, params *BrokerLoginParams, reqEditors ...RequestEditorFn) (*BrokerLoginResponse, error)

	// BrokerSSOStartWithResponse Start a broker authentication method
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /broker/stytch/sso/start (the `BrokerSSOStart` operationId).
	BrokerSSOStartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*BrokerSSOStartResponse, error)

	// HealthzWithResponse Liveness probe
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /healthz (the `Healthz` operationId).
	HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzResponse, error)

	// OauthAuthorizeWithResponse Start an OAuth authorization request
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /oauth/authorize (the `OauthAuthorize` operationId).
	OauthAuthorizeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*OauthAuthorizeResponse, error)

	// ReadyzWithResponse Readiness probe (database ping)
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /readyz (the `Readyz` operationId).
	ReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReadyzResponse, error)
}

// BrokerCallbackResponse303Headers the declared response headers of an HTTP 303 response for BrokerCallback
type BrokerCallbackResponse303Headers struct {
	CacheControl            *string
	Location                *string
	Pragma                  *string
	ReferrerPolicy          *string
	SetCookie               *string
	StrictTransportSecurity *string
	XContentTypeOptions     *string
}

type BrokerCallbackResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *ErrorModel
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *ErrorModel
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *ErrorModel
	// ApplicationproblemJSON503 the response for an HTTP 503 `application/problem+json` response
	ApplicationproblemJSON503 *ErrorModel
	// Headers303 the parsed response headers for an HTTP 303 response
	Headers303 *BrokerCallbackResponse303Headers
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r BrokerCallbackResponse) GetApplicationproblemJSON400() *ErrorModel {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r BrokerCallbackResponse) GetApplicationproblemJSON422() *ErrorModel {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r BrokerCallbackResponse) GetApplicationproblemJSON500() *ErrorModel {
	return r.ApplicationproblemJSON500
}

// GetApplicationproblemJSON503 returns the response for an HTTP 503 `application/problem+json` response
func (r BrokerCallbackResponse) GetApplicationproblemJSON503() *ErrorModel {
	return r.ApplicationproblemJSON503
}

// GetBody returns the raw response body bytes
func (r BrokerCallbackResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r BrokerCallbackResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BrokerCallbackResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BrokerCallbackResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// BrokerEmailStartResponse200Headers the declared response headers of an HTTP 200 response for BrokerEmailStart
type BrokerEmailStartResponse200Headers struct {
	CacheControl            *string
	Location                *string
	Pragma                  *string
	ReferrerPolicy          *string
	StrictTransportSecurity *string
	XContentTypeOptions     *string
}

type BrokerEmailStartResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *StartOutBody
	// ApplicationproblemJSON303 the response for an HTTP 303 `application/problem+json` response
	ApplicationproblemJSON303 *ErrorModel
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *ErrorModel
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *ErrorModel
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *BrokerEmailStartResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r BrokerEmailStartResponse) GetJSON200() *StartOutBody {
	return r.JSON200
}

// GetApplicationproblemJSON303 returns the response for an HTTP 303 `application/problem+json` response
func (r BrokerEmailStartResponse) GetApplicationproblemJSON303() *ErrorModel {
	return r.ApplicationproblemJSON303
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r BrokerEmailStartResponse) GetApplicationproblemJSON400() *ErrorModel {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r BrokerEmailStartResponse) GetApplicationproblemJSON500() *ErrorModel {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r BrokerEmailStartResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r BrokerEmailStartResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BrokerEmailStartResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BrokerEmailStartResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// BrokerEmailVerifyResponse200Headers the declared response headers of an HTTP 200 response for BrokerEmailVerify
type BrokerEmailVerifyResponse200Headers struct {
	CacheControl            *string
	Location                *string
	Pragma                  *string
	ReferrerPolicy          *string
	StrictTransportSecurity *string
	XContentTypeOptions     *string
}

type BrokerEmailVerifyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *StartOutBody
	// ApplicationproblemJSON303 the response for an HTTP 303 `application/problem+json` response
	ApplicationproblemJSON303 *ErrorModel
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *ErrorModel
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *ErrorModel
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *BrokerEmailVerifyResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r BrokerEmailVerifyResponse) GetJSON200() *StartOutBody {
	return r.JSON200
}

// GetApplicationproblemJSON303 returns the response for an HTTP 303 `application/problem+json` response
func (r BrokerEmailVerifyResponse) GetApplicationproblemJSON303() *ErrorModel {
	return r.ApplicationproblemJSON303
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r BrokerEmailVerifyResponse) GetApplicationproblemJSON400() *ErrorModel {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r BrokerEmailVerifyResponse) GetApplicationproblemJSON500() *ErrorModel {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r BrokerEmailVerifyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r BrokerEmailVerifyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BrokerEmailVerifyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BrokerEmailVerifyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type BrokerLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *ErrorModel
	// ApplicationproblemJSON422 the response for an HTTP 422 `application/problem+json` response
	ApplicationproblemJSON422 *ErrorModel
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *ErrorModel
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r BrokerLoginResponse) GetApplicationproblemJSON400() *ErrorModel {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON422 returns the response for an HTTP 422 `application/problem+json` response
func (r BrokerLoginResponse) GetApplicationproblemJSON422() *ErrorModel {
	return r.ApplicationproblemJSON422
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r BrokerLoginResponse) GetApplicationproblemJSON500() *ErrorModel {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r BrokerLoginResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r BrokerLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BrokerLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BrokerLoginResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// BrokerSSOStartResponse200Headers the declared response headers of an HTTP 200 response for BrokerSSOStart
type BrokerSSOStartResponse200Headers struct {
	CacheControl            *string
	Location                *string
	Pragma                  *string
	ReferrerPolicy          *string
	StrictTransportSecurity *string
	XContentTypeOptions     *string
}

type BrokerSSOStartResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *StartOutBody
	// ApplicationproblemJSON303 the response for an HTTP 303 `application/problem+json` response
	ApplicationproblemJSON303 *ErrorModel
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *ErrorModel
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *ErrorModel
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *BrokerSSOStartResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r BrokerSSOStartResponse) GetJSON200() *StartOutBody {
	return r.JSON200
}

// GetApplicationproblemJSON303 returns the response for an HTTP 303 `application/problem+json` response
func (r BrokerSSOStartResponse) GetApplicationproblemJSON303() *ErrorModel {
	return r.ApplicationproblemJSON303
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r BrokerSSOStartResponse) GetApplicationproblemJSON400() *ErrorModel {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r BrokerSSOStartResponse) GetApplicationproblemJSON500() *ErrorModel {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r BrokerSSOStartResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r BrokerSSOStartResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BrokerSSOStartResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BrokerSSOStartResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type HealthzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *HealthOutBody
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *ErrorModel
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r HealthzResponse) GetJSON200() *HealthOutBody {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r HealthzResponse) GetApplicationproblemJSONDefault() *ErrorModel {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r HealthzResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r HealthzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// OauthAuthorizeResponse303Headers the declared response headers of an HTTP 303 response for OauthAuthorize
type OauthAuthorizeResponse303Headers struct {
	CacheControl            *string
	Location                *string
	Pragma                  *string
	ReferrerPolicy          *string
	SetCookie               *string
	StrictTransportSecurity *string
	XContentTypeOptions     *string
}

type OauthAuthorizeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *ErrorModel
	// ApplicationproblemJSON413 the response for an HTTP 413 `application/problem+json` response
	ApplicationproblemJSON413 *ErrorModel
	// ApplicationproblemJSON500 the response for an HTTP 500 `application/problem+json` response
	ApplicationproblemJSON500 *ErrorModel
	// Headers303 the parsed response headers for an HTTP 303 response
	Headers303 *OauthAuthorizeResponse303Headers
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r OauthAuthorizeResponse) GetApplicationproblemJSON400() *ErrorModel {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON413 returns the response for an HTTP 413 `application/problem+json` response
func (r OauthAuthorizeResponse) GetApplicationproblemJSON413() *ErrorModel {
	return r.ApplicationproblemJSON413
}

// GetApplicationproblemJSON500 returns the response for an HTTP 500 `application/problem+json` response
func (r OauthAuthorizeResponse) GetApplicationproblemJSON500() *ErrorModel {
	return r.ApplicationproblemJSON500
}

// GetBody returns the raw response body bytes
func (r OauthAuthorizeResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r OauthAuthorizeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OauthAuthorizeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r OauthAuthorizeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReadyzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ReadyOutBody
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *ErrorModel
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ReadyzResponse) GetJSON200() *ReadyOutBody {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r ReadyzResponse) GetApplicationproblemJSONDefault() *ErrorModel {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r ReadyzResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ReadyzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReadyzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReadyzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// BrokerCallbackWithResponse Complete a broker callback
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /broker/stytch/callback (the `BrokerCallback` operationId).
func (c *ClientWithResponses) BrokerCallbackWithResponse(ctx context.Context, params *BrokerCallbackParams, reqEditors ...RequestEditorFn) (*BrokerCallbackResponse, error) {
	rsp, err := c.BrokerCallback(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBrokerCallbackResponse(rsp)
}

// BrokerEmailStartWithResponse Start a broker authentication method
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /broker/stytch/email/start (the `BrokerEmailStart` operationId).
func (c *ClientWithResponses) BrokerEmailStartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*BrokerEmailStartResponse, error) {
	rsp, err := c.BrokerEmailStart(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBrokerEmailStartResponse(rsp)
}

// BrokerEmailVerifyWithResponse Start a broker authentication method
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /broker/stytch/email/verify (the `BrokerEmailVerify` operationId).
func (c *ClientWithResponses) BrokerEmailVerifyWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*BrokerEmailVerifyResponse, error) {
	rsp, err := c.BrokerEmailVerify(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBrokerEmailVerifyResponse(rsp)
}

// BrokerLoginWithResponse Broker login discovery
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /broker/stytch/login (the `BrokerLogin` operationId).
func (c *ClientWithResponses) BrokerLoginWithResponse(ctx context.Context, params *BrokerLoginParams, reqEditors ...RequestEditorFn) (*BrokerLoginResponse, error) {
	rsp, err := c.BrokerLogin(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBrokerLoginResponse(rsp)
}

// BrokerSSOStartWithResponse Start a broker authentication method
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /broker/stytch/sso/start (the `BrokerSSOStart` operationId).
func (c *ClientWithResponses) BrokerSSOStartWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*BrokerSSOStartResponse, error) {
	rsp, err := c.BrokerSSOStart(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBrokerSSOStartResponse(rsp)
}

// HealthzWithResponse Liveness probe
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /healthz (the `Healthz` operationId).
func (c *ClientWithResponses) HealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzResponse, error) {
	rsp, err := c.Healthz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthzResponse(rsp)
}

// OauthAuthorizeWithResponse Start an OAuth authorization request
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /oauth/authorize (the `OauthAuthorize` operationId).
func (c *ClientWithResponses) OauthAuthorizeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*OauthAuthorizeResponse, error) {
	rsp, err := c.OauthAuthorize(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOauthAuthorizeResponse(rsp)
}

// ReadyzWithResponse Readiness probe (database ping)
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /readyz (the `Readyz` operationId).
func (c *ClientWithResponses) ReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ReadyzResponse, error) {
	rsp, err := c.Readyz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReadyzResponse(rsp)
}

// ParseBrokerCallbackResponse parses an HTTP response from a BrokerCallbackWithResponse call
func ParseBrokerCallbackResponse(rsp *http.Response) (*BrokerCallbackResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BrokerCallbackResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 303:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON503 = &dest

	}

	switch {
	case rsp.StatusCode == 303:
		var headers BrokerCallbackResponse303Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		if values := rsp.Header.Values("Location"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Location", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Location = &value
		}
		if values := rsp.Header.Values("Pragma"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Pragma", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Pragma = &value
		}
		if values := rsp.Header.Values("Referrer-Policy"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Referrer-Policy", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ReferrerPolicy = &value
		}
		if values := rsp.Header.Values("Set-Cookie"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Set-Cookie", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.SetCookie = &value
		}
		if values := rsp.Header.Values("Strict-Transport-Security"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Strict-Transport-Security", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.StrictTransportSecurity = &value
		}
		if values := rsp.Header.Values("X-Content-Type-Options"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Content-Type-Options", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XContentTypeOptions = &value
		}
		response.Headers303 = &headers
	}

	return response, nil
}

// ParseBrokerEmailStartResponse parses an HTTP response from a BrokerEmailStartWithResponse call
func ParseBrokerEmailStartResponse(rsp *http.Response) (*BrokerEmailStartResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BrokerEmailStartResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StartOutBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 303:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON303 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers BrokerEmailStartResponse200Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		if values := rsp.Header.Values("Location"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Location", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Location = &value
		}
		if values := rsp.Header.Values("Pragma"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Pragma", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Pragma = &value
		}
		if values := rsp.Header.Values("Referrer-Policy"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Referrer-Policy", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ReferrerPolicy = &value
		}
		if values := rsp.Header.Values("Strict-Transport-Security"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Strict-Transport-Security", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.StrictTransportSecurity = &value
		}
		if values := rsp.Header.Values("X-Content-Type-Options"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Content-Type-Options", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XContentTypeOptions = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParseBrokerEmailVerifyResponse parses an HTTP response from a BrokerEmailVerifyWithResponse call
func ParseBrokerEmailVerifyResponse(rsp *http.Response) (*BrokerEmailVerifyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BrokerEmailVerifyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StartOutBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 303:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON303 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers BrokerEmailVerifyResponse200Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		if values := rsp.Header.Values("Location"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Location", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Location = &value
		}
		if values := rsp.Header.Values("Pragma"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Pragma", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Pragma = &value
		}
		if values := rsp.Header.Values("Referrer-Policy"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Referrer-Policy", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ReferrerPolicy = &value
		}
		if values := rsp.Header.Values("Strict-Transport-Security"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Strict-Transport-Security", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.StrictTransportSecurity = &value
		}
		if values := rsp.Header.Values("X-Content-Type-Options"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Content-Type-Options", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XContentTypeOptions = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParseBrokerLoginResponse parses an HTTP response from a BrokerLoginWithResponse call
func ParseBrokerLoginResponse(rsp *http.Response) (*BrokerLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BrokerLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 200:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseBrokerSSOStartResponse parses an HTTP response from a BrokerSSOStartWithResponse call
func ParseBrokerSSOStartResponse(rsp *http.Response) (*BrokerSSOStartResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BrokerSSOStartResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StartOutBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 303:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON303 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers BrokerSSOStartResponse200Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		if values := rsp.Header.Values("Location"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Location", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Location = &value
		}
		if values := rsp.Header.Values("Pragma"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Pragma", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Pragma = &value
		}
		if values := rsp.Header.Values("Referrer-Policy"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Referrer-Policy", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ReferrerPolicy = &value
		}
		if values := rsp.Header.Values("Strict-Transport-Security"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Strict-Transport-Security", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.StrictTransportSecurity = &value
		}
		if values := rsp.Header.Values("X-Content-Type-Options"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Content-Type-Options", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XContentTypeOptions = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParseHealthzResponse parses an HTTP response from a HealthzWithResponse call
func ParseHealthzResponse(rsp *http.Response) (*HealthzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthOutBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseOauthAuthorizeResponse parses an HTTP response from a OauthAuthorizeWithResponse call
func ParseOauthAuthorizeResponse(rsp *http.Response) (*OauthAuthorizeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OauthAuthorizeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 303:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	switch {
	case rsp.StatusCode == 303:
		var headers OauthAuthorizeResponse303Headers
		if values := rsp.Header.Values("Cache-Control"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Cache-Control", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.CacheControl = &value
		}
		if values := rsp.Header.Values("Location"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Location", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Location = &value
		}
		if values := rsp.Header.Values("Pragma"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Pragma", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Pragma = &value
		}
		if values := rsp.Header.Values("Referrer-Policy"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Referrer-Policy", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ReferrerPolicy = &value
		}
		if values := rsp.Header.Values("Set-Cookie"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Set-Cookie", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.SetCookie = &value
		}
		if values := rsp.Header.Values("Strict-Transport-Security"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Strict-Transport-Security", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.StrictTransportSecurity = &value
		}
		if values := rsp.Header.Values("X-Content-Type-Options"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Content-Type-Options", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.XContentTypeOptions = &value
		}
		response.Headers303 = &headers
	}

	return response, nil
}

// ParseReadyzResponse parses an HTTP response from a ReadyzWithResponse call
func ParseReadyzResponse(rsp *http.Response) (*ReadyzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReadyzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReadyOutBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
