package identityclient_test

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	identityclient "github.com/aleksclark/primer/identity/client"
)

const generatedMarker = "Code generated by github.com/oapi-codegen/oapi-codegen/v2"

var requiredIB1ClientOps = []string{
	"Jwks",
	"OauthAuthorizationServer",
	"BrokerCallback",
	"BrokerEmailStart",
	"BrokerEmailVerify",
	"BrokerLogin",
	"BrokerSSOStart",
	"Healthz",
	"OauthAuthorize",
	"OauthTokenWithBody",
	"OauthTokenWithFormdataBody",
	"Readyz",
}

var forbiddenGeneratedTypeNeedles = []string{
	"SessionJWT",
	"SessionJwt",
	"SessionToken",
	"IDToken",
	"IdToken",
	"ProviderPayload",
}

func TestGeneratedMarkerPresent(t *testing.T) {
	t.Parallel()

	src := readGeneratedClient(t)
	assert.Contains(t, src, generatedMarker)
	assert.Contains(t, src, "DO NOT EDIT.")
	assert.Contains(t, src, "package identityclient")
}

func TestGeneratedClientHasExactIB1Operations(t *testing.T) {
	t.Parallel()

	got := clientInterfaceMethods(t, parseGeneratedFile(t))
	assert.Equal(t, requiredIB1ClientOps, got)
}

func TestGeneratedClientHasExactlyOneOauthTokenOperation(t *testing.T) {
	t.Parallel()

	got := clientInterfaceMethods(t, parseGeneratedFile(t))
	var tokenOps []string
	for _, name := range got {
		if strings.HasPrefix(name, "OauthToken") {
			tokenOps = append(tokenOps, name)
		}
	}
	require.NotEmpty(t, tokenOps)

	src := readGeneratedClient(t)
	assert.GreaterOrEqual(t, strings.Count(src, "(the `OauthToken` operationId)"), 1)
	assert.NotContains(t, src, "application/octet-stream")
	assert.NotContains(t, src, "OauthTokenWithOctetStream")
	assert.NotContains(t, src, "contentMediaType: application/octet-stream")
	assert.ElementsMatch(t, []string{"OauthTokenWithBody", "OauthTokenWithFormdataBody"}, tokenOps)
}

func TestGeneratedClientCompiles(t *testing.T) {
	t.Parallel()

	c, err := identityclient.NewClient("http://127.0.0.1")
	require.NoError(t, err)
	require.NotNil(t, c)
	var _ identityclient.ClientInterface = c
}

func TestGeneratedClientHasNoTokenJWKSOrProviderResponseTypes(t *testing.T) {
	t.Parallel()

	file := parseGeneratedFile(t)
	var names []string
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			names = append(names, ts.Name.Name)
			for _, needle := range forbiddenGeneratedTypeNeedles {
				if strings.Contains(ts.Name.Name, needle) {
					t.Errorf("forbidden generated type %q contains %q", ts.Name.Name, needle)
				}
			}
		}
	}
	require.NotEmpty(t, names)

	src := strings.ToLower(readGeneratedClient(t))
	assert.Contains(t, src, "/oauth/token")
	assert.Contains(t, src, "access_token")
	assert.Contains(t, src, "refresh_token")
	assert.NotContains(t, src, "application/octet-stream")
	for _, needle := range []string{
		"session_jwt",
		"session_token",
		"id_token",
		"provider_payload",
		"/oauth/revoke",
		"client_credentials",
	} {
		assert.NotContains(t, src, needle)
	}
	assert.Contains(t, src, "/.well-known/jwks.json")
	assert.Contains(t, src, "/.well-known/oauth-authorization-server")
	assert.NotContains(t, src, "\"/jwks\"")
	assert.NotContains(t, src, "/oauth/jwks")
}

func TestGenerateClientTwiceIsByteEqual(t *testing.T) {
	first := generateClient(t, filepath.Join(t.TempDir(), "a.gen.go"))
	second := generateClient(t, filepath.Join(t.TempDir(), "b.gen.go"))
	assert.Equal(t, first, second)
	assert.NotEmpty(t, first)
}

func TestGeneratedClientMatchesPinnedRegen(t *testing.T) {
	want := []byte(readGeneratedClient(t))
	got := generateClient(t, filepath.Join(t.TempDir(), "client.gen.go"))
	assert.Equal(t, want, got)
}

func readGeneratedClient(t *testing.T) string {
	t.Helper()
	raw, err := os.ReadFile(generatedClientPath(t))
	require.NoError(t, err)
	return string(raw)
}

func generatedClientPath(t *testing.T) string {
	t.Helper()
	return filepath.Join(clientDir(t), "client.gen.go")
}

func clientDir(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	require.True(t, ok)
	return filepath.Dir(file)
}

func moduleRoot(t *testing.T) string {
	t.Helper()
	return filepath.Clean(filepath.Join(clientDir(t), ".."))
}

func parseGeneratedFile(t *testing.T) *ast.File {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, generatedClientPath(t), nil, 0)
	require.NoError(t, err)
	return file
}

func clientInterfaceMethods(t *testing.T, file *ast.File) []string {
	t.Helper()
	var names []string
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != "ClientInterface" {
				continue
			}
			iface, ok := ts.Type.(*ast.InterfaceType)
			require.True(t, ok, "ClientInterface must be an interface")
			for _, method := range iface.Methods.List {
				require.Len(t, method.Names, 1)
				names = append(names, method.Names[0].Name)
			}
		}
	}
	require.NotEmpty(t, names, "ClientInterface methods")
	return names
}

func countExact(names []string, want string) int {
	n := 0
	for _, name := range names {
		if name == want {
			n++
		}
	}
	return n
}

func generateClient(t *testing.T, out string) []byte {
	t.Helper()
	cmd := exec.Command(
		"go", "tool", "oapi-codegen",
		"-package", "identityclient",
		"-generate", "types,client",
		"-o", out,
		"openapi.yaml",
	)
	cmd.Dir = moduleRoot(t)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	err := cmd.Run()
	require.NoError(t, err, "oapi-codegen failed: %s", stderr.String())
	raw, err := os.ReadFile(out)
	require.NoError(t, err)
	return raw
}
