package api_test

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/aleksclark/primer/agents/internal/api"
)

// TestOpenAPIDeterministic verifies that the committed openapi.yaml and
// openapi30.yaml match what the current handler signatures produce. A diff
// here means a handler was changed without re-running `make openapi`.
//
// The test is skipped when running with -short or when the committed files are
// absent (e.g. first generation run), so it never blocks initial bootstrap.
func TestOpenAPIDeterministic(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping OpenAPI drift check in -short mode")
	}

	_, thisFile, _, ok := runtime.Caller(0)
	require.True(t, ok)
	moduleRoot := filepath.Join(filepath.Dir(thisFile), "..", "..")

	for _, tc := range []struct {
		name      string
		committed string
		downgrade bool
	}{
		{"openapi.yaml (3.1)", "openapi.yaml", false},
		{"openapi30.yaml (3.0)", "openapi30.yaml", true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			committed := filepath.Join(moduleRoot, tc.committed)
			if _, err := os.Stat(committed); os.IsNotExist(err) {
				t.Skipf("committed %s not found; run `make openapi` first", tc.committed)
			}

			want, err := os.ReadFile(committed)
			require.NoError(t, err, "read committed spec")

			humaAPI := api.NewSpec(api.Options{})
			var got []byte
			if tc.downgrade {
				got, err = humaAPI.OpenAPI().DowngradeYAML()
			} else {
				got, err = humaAPI.OpenAPI().YAML()
			}
			require.NoError(t, err, "generate spec")

			if !bytes.Equal(want, got) {
				t.Errorf("%s is stale — run `make openapi` to regenerate\ndiff (first 512 bytes):\n%s",
					tc.committed, diffSnippet(want, got))
			}
		})
	}
}

// TestNoDuplicateDTOs verifies the generated Go client import path and that
// no hand-written duplicate request/response structs exist alongside the
// generated code.
func TestNoDuplicateDTOs(t *testing.T) {
	t.Parallel()
	_, thisFile, _, ok := runtime.Caller(0)
	require.True(t, ok)
	clientDir := filepath.Join(filepath.Dir(thisFile), "..", "..", "client", "go")

	// client.gen.go must exist (generated, not hand-written).
	genFile := filepath.Join(clientDir, "client.gen.go")
	_, err := os.Stat(genFile)
	require.NoError(t, err, "client/go/client.gen.go must exist (run `make clients-go`)")

	content, err := os.ReadFile(genFile)
	require.NoError(t, err)
	assert.Contains(t, string(content), "Code generated by github.com/oapi-codegen",
		"client.gen.go must carry oapi-codegen generation header")

	// client.go (facade) must not redefine the wire types.
	facade, err := os.ReadFile(filepath.Join(clientDir, "client.go"))
	require.NoError(t, err)
	for _, forbidden := range []string{"type RunResponse struct", "type SessionResponse struct", "type EventResponse struct"} {
		assert.NotContains(t, string(facade), forbidden,
			"client.go must not hand-write %q (generated types only)", forbidden)
	}
}

// TestNoRawTransportImports verifies that no production file in the main
// module imports raw HTTP transport or handwritten consumer endpoints.
func TestNoRawTransportImports(t *testing.T) {
	t.Parallel()
	_, thisFile, _, ok := runtime.Caller(0)
	require.True(t, ok)
	moduleRoot := filepath.Join(filepath.Dir(thisFile), "..", "..")

	// Scan internal/ for suspicious patterns that would indicate a consumer
	// bypassing the generated client.
	cmd := exec.Command("grep", "-rn",
		`http\.NewRequest.*agents/v1`, // raw request to agents endpoint
		filepath.Join(moduleRoot, "internal"))
	out, _ := cmd.CombinedOutput()
	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	for _, line := range lines {
		if line == "" {
			continue
		}
		assert.Failf(t, "raw consumer transport found", "found potential raw transport call: %s", line)
	}
}

func diffSnippet(want, got []byte) string {
	w := strings.Split(string(want), "\n")
	g := strings.Split(string(got), "\n")
	var sb strings.Builder
	for i := 0; i < len(w) && i < len(g); i++ {
		if w[i] != g[i] {
			sb.WriteString("- " + w[i] + "\n")
			sb.WriteString("+ " + g[i] + "\n")
			if sb.Len() > 512 {
				break
			}
		}
	}
	if sb.Len() == 0 && len(w) != len(g) {
		sb.WriteString("(line count differs)")
	}
	return sb.String()
}
