package directplay_test

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/aleksclark/primer/server/internal/tv/directplay"
)

func TestEvaluate(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		video  string
		audio  string
		ok     bool
		notes  string
		issues []string
	}{
		{
			name:  "h264 aac is direct-play OK",
			video: "h264",
			audio: "aac",
			ok:    true,
		},
		{
			name:  "stale EAC3 false becomes true",
			video: "h264",
			audio: "eac3",
			ok:    true,
		},
		{
			name:  "stale DTS false becomes true",
			video: "hevc",
			audio: "dts",
			ok:    true,
		},
		{
			name:  "AC3 is allowed via FFmpeg fallback",
			video: "h264",
			audio: "ac3",
			ok:    true,
		},
		{
			name:   "unsupported audio true becomes false",
			video:  "h264",
			audio:  "truehd",
			ok:     false,
			notes:  "audio codec truehd",
			issues: []string{"audio codec truehd"},
		},
		{
			name:   "unsupported video true becomes false",
			video:  "av1",
			audio:  "aac",
			ok:     false,
			notes:  "video codec av1",
			issues: []string{"video codec av1"},
		},
		{
			name:   "both codecs unsupported",
			video:  "av1",
			audio:  "truehd",
			ok:     false,
			notes:  "video codec av1; audio codec truehd",
			issues: []string{"video codec av1", "audio codec truehd"},
		},
		{
			name:  "blank codecs are ignored (unknown)",
			video: "",
			audio: "",
			ok:    true,
		},
		{
			name:  "codec matching is case-insensitive",
			video: "H264",
			audio: "EAC3",
			ok:    true,
		},
		{
			name:   "issue notes preserve original codec casing",
			video:  "AV1",
			audio:  "TrueHD",
			ok:     false,
			notes:  "video codec AV1; audio codec TrueHD",
			issues: []string{"video codec AV1", "audio codec TrueHD"},
		},
		{
			name:  "h265 alias is allowed",
			video: "h265",
			audio: "flac",
			ok:    true,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			eval := directplay.Evaluate(tc.video, tc.audio)
			assert.Equal(t, tc.ok, eval.OK)
			assert.Equal(t, tc.notes, eval.Notes)
			if tc.issues == nil {
				assert.Empty(t, eval.Issues)
			} else {
				assert.Equal(t, tc.issues, eval.Issues)
			}
		})
	}
}

func TestIsAutoGeneratedNote(t *testing.T) {
	t.Parallel()

	tests := []struct {
		notes string
		auto  bool
	}{
		{notes: "", auto: true},
		{notes: "   ", auto: true},
		{notes: "video codec av1", auto: true},
		{notes: "audio codec truehd", auto: true},
		{notes: "video codec av1; audio codec truehd", auto: true},
		{notes: "audio codec eac3", auto: true},
		{notes: "bad encode, re-rip from disc", auto: false},
		{notes: "video codec av1 — needs re-encode", auto: false},
		{notes: "manual: skip for now", auto: false},
		{notes: "audio codec truehd; curator: keep blocked", auto: false},
	}

	for _, tc := range tests {
		t.Run(tc.notes, func(t *testing.T) {
			t.Parallel()
			name := tc.notes
			if name == "" {
				name = "empty"
			}
			assert.Equal(t, tc.auto, directplay.IsAutoGeneratedNote(tc.notes), name)
		})
	}
}

func TestReconcileQualityNotes(t *testing.T) {
	t.Parallel()

	t.Run("stale auto-note cleanup when EAC3 becomes OK", func(t *testing.T) {
		t.Parallel()
		eval := directplay.Evaluate("h264", "eac3")
		require.True(t, eval.OK)
		next, update := directplay.ReconcileQualityNotes("audio codec eac3", eval)
		assert.True(t, update)
		assert.Empty(t, next)
	})

	t.Run("stale auto-note cleanup when DTS becomes OK", func(t *testing.T) {
		t.Parallel()
		eval := directplay.Evaluate("hevc", "dts")
		require.True(t, eval.OK)
		next, update := directplay.ReconcileQualityNotes("audio codec dts", eval)
		assert.True(t, update)
		assert.Empty(t, next)
	})

	t.Run("auto-note replaced when unsupported codec appears", func(t *testing.T) {
		t.Parallel()
		eval := directplay.Evaluate("h264", "truehd")
		require.False(t, eval.OK)
		next, update := directplay.ReconcileQualityNotes("", eval)
		assert.True(t, update)
		assert.Equal(t, "audio codec truehd", next)
	})

	t.Run("manual note preservation when becoming OK", func(t *testing.T) {
		t.Parallel()
		eval := directplay.Evaluate("h264", "eac3")
		require.True(t, eval.OK)
		manual := "curator: keep for family movie night review"
		next, update := directplay.ReconcileQualityNotes(manual, eval)
		assert.False(t, update)
		assert.Equal(t, manual, next)
	})

	t.Run("manual note preservation when still blocked", func(t *testing.T) {
		t.Parallel()
		eval := directplay.Evaluate("av1", "aac")
		require.False(t, eval.OK)
		manual := "wait for AV1 hardware on next box revision"
		next, update := directplay.ReconcileQualityNotes(manual, eval)
		assert.False(t, update)
		assert.Equal(t, manual, next)
	})

	t.Run("no write when auto-note already matches", func(t *testing.T) {
		t.Parallel()
		eval := directplay.Evaluate("av1", "aac")
		next, update := directplay.ReconcileQualityNotes("video codec av1", eval)
		assert.False(t, update)
		assert.Equal(t, "video codec av1", next)
	})
}

func TestAllowlistsMatchExpectedAndroidCapability(t *testing.T) {
	t.Parallel()
	assert.Equal(t, []string{"h264", "hevc", "h265", "mpeg4", "vp8", "vp9"}, directplay.VideoAllowlist)
	assert.Equal(t, []string{"aac", "mp3", "ac3", "eac3", "dts", "opus", "vorbis", "flac"}, directplay.AudioAllowlist)
	assert.NotContains(t, directplay.AudioAllowlist, "truehd")
	assert.NotContains(t, directplay.VideoAllowlist, "av1")
}
