// Package directplay evaluates whether a media item can direct-play on the
// Android TV client without Jellyfin transcoding.
//
// Video codecs rely on SoC hardware decoders. AC3/EAC3/DTS are handled by the
// app's bundled Media3 FFmpeg software fallback (LGPL). Keep the allowlists
// aligned with tv-web/src/lib/directPlay.ts — the tv-web check-direct-play
// script verifies both sides stay in sync.
package directplay

import (
	"regexp"
	"strings"
)

// Video codecs the Android client can direct-play (SoC hardware).
// Jellyfin reports these lowercase (e.g. "h264", "hevc").
var VideoAllowlist = []string{"h264", "hevc", "h265", "mpeg4", "vp8", "vp9"}

// Audio codecs the Android client can direct-play. AAC/MP3/opus/vorbis/flac
// use platform MediaCodec; ac3/eac3/dts use the bundled Media3 FFmpeg extension.
var AudioAllowlist = []string{"aac", "mp3", "ac3", "eac3", "dts", "opus", "vorbis", "flac"}

var (
	videoSet = toSet(VideoAllowlist)
	audioSet = toSet(AudioAllowlist)

	// Matches notes produced by Evaluate / tv-web directPlayIssues, e.g.
	// "video codec av1", "audio codec truehd", or both joined by "; ".
	// Codec tokens are non-space (Jellyfin names like "eac3", "truehd").
	autoNoteRE = regexp.MustCompile(
		`^(?:video codec \S+|audio codec \S+)(?:; (?:video codec \S+|audio codec \S+))*$`,
	)
)

// Evaluation is the direct-play decision for a pair of codecs.
type Evaluation struct {
	// OK is true when every present codec is on the allowlist (or blank).
	OK bool
	// Issues lists human-readable blockers (empty when OK).
	Issues []string
	// Notes is Issues joined with "; " — the auto-generated quality_notes form.
	Notes string
}

// Evaluate decides direct-play eligibility from Jellyfin codec strings.
// Blank codecs are ignored (unknown), matching the admin SPA import helper.
func Evaluate(videoCodec, audioCodec string) Evaluation {
	var issues []string
	if videoCodec != "" && !videoSet[strings.ToLower(videoCodec)] {
		issues = append(issues, "video codec "+videoCodec)
	}
	if audioCodec != "" && !audioSet[strings.ToLower(audioCodec)] {
		issues = append(issues, "audio codec "+audioCodec)
	}
	return Evaluation{
		OK:     len(issues) == 0,
		Issues: issues,
		Notes:  strings.Join(issues, "; "),
	}
}

// IsAutoGeneratedNote reports whether notes are blank or match the
// machine-written codec-issue format. Manual curator notes must not match.
func IsAutoGeneratedNote(notes string) bool {
	trimmed := strings.TrimSpace(notes)
	if trimmed == "" {
		return true
	}
	return autoNoteRE.MatchString(trimmed)
}

// IsStaleAllowlistNote reports whether quality_notes is safe evidence for a
// false→true direct_play_ok repair after an allowlist expansion.
//
// Requirements (all must hold):
//  1. notes are nonblank
//  2. notes match the strict auto-generated codec format
//  3. every referenced codec token is currently on the matching allowlist
//
// So "audio codec eac3" / "audio codec dts" authorize repair once those codecs
// are allowlisted, but "audio codec truehd" and mixed notes that still name an
// unsupported codec (e.g. "video codec av1; audio codec eac3") do not — even
// though they are auto-shaped. This closes the multi-sync hole where a blank
// curator withhold gains a truehd auto note, then a later eac3 sync would
// otherwise treat any auto note as stale-allowlist evidence.
func IsStaleAllowlistNote(notes string) bool {
	trimmed := strings.TrimSpace(notes)
	if trimmed == "" {
		return false
	}
	if !autoNoteRE.MatchString(trimmed) {
		return false
	}
	for _, part := range strings.Split(trimmed, "; ") {
		codec, kind, ok := parseAutoCodecIssue(part)
		if !ok {
			return false
		}
		switch kind {
		case "video":
			if !videoSet[strings.ToLower(codec)] {
				return false
			}
		case "audio":
			if !audioSet[strings.ToLower(codec)] {
				return false
			}
		default:
			return false
		}
	}
	return true
}

// parseAutoCodecIssue extracts the codec token and kind ("video"/"audio") from
// a single auto-generated issue segment like "audio codec eac3".
func parseAutoCodecIssue(part string) (codec, kind string, ok bool) {
	const videoPrefix = "video codec "
	const audioPrefix = "audio codec "
	switch {
	case strings.HasPrefix(part, videoPrefix):
		codec = strings.TrimSpace(strings.TrimPrefix(part, videoPrefix))
		if codec == "" || strings.ContainsAny(codec, " 	") {
			return "", "", false
		}
		return codec, "video", true
	case strings.HasPrefix(part, audioPrefix):
		codec = strings.TrimSpace(strings.TrimPrefix(part, audioPrefix))
		if codec == "" || strings.ContainsAny(codec, " 	") {
			return "", "", false
		}
		return codec, "audio", true
	default:
		return "", "", false
	}
}

// ReconcileQualityNotes returns the quality_notes value that should be stored
// after a policy evaluation, and whether the column needs updating.
//
// Manual notes are never overwritten. Blank or auto-generated notes are
// replaced with the evaluation's notes (cleared when direct-play is OK).
func ReconcileQualityNotes(currentNotes string, eval Evaluation) (next string, update bool) {
	if !IsAutoGeneratedNote(currentNotes) {
		return currentNotes, false
	}
	if currentNotes == eval.Notes {
		return currentNotes, false
	}
	return eval.Notes, true
}

func toSet(items []string) map[string]bool {
	out := make(map[string]bool, len(items))
	for _, item := range items {
		out[item] = true
	}
	return out
}
