import { useState } from 'react';
import { library, saveUnit, importUnit, saveTemplate, shares, share, revoke, problem } from '../api/collaboration';
import type { Model } from '../api/collaboration';
import { Notice, Pager, useRemote } from './common';

export function UnitLibrary({workspaceId,revisionId,nodes,edges,editable,onChanged}:{workspaceId:string;revisionId:string;nodes:Model<'PlanNode'>[];edges:Model<'PlanEdge'>[];editable:boolean;onChanged:()=>void}){
 const [offset,setOffset]=useState(0);const [unit,setUnit]=useState('');const [name,setName]=useState('');const [templateName,setTemplateName]=useState('');const [code,setCode]=useState('');const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
 const result=useRemote(signal=>library(workspaceId,offset,signal),[workspaceId,offset]);
 async function act(action:()=>Promise<unknown>,success:string){setSaving(true);setMessage('');try{await action();setMessage(success);result.reload();onChanged()}catch(e){setMessage(problem(e))}finally{setSaving(false)}}
 function templateSeed(){
  const outcomes=nodes.filter(n=>n.kind==='outcome').map(n=>({code:n.id,title:n.title}));
  const units=nodes.filter(n=>n.kind==='unit').map(n=>({code:n.id,title:n.title,outcomeCodes:edges.filter(e=>e.kind==='parent_child'&&e.fromNodeId===n.id&&outcomes.some(o=>o.code===e.toNodeId)).map(e=>e.toNodeId)}));
  return {outcomes,units};
 }
 return <section className="collab-section"><h3>Reusable units and templates</h3><form className="collab-form" onSubmit={e=>{e.preventDefault();void act(()=>saveUnit(workspaceId,revisionId,unit,name),'Unit snapshot saved.')}}><label htmlFor="library-unit">Unit to save</label><select id="library-unit" value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Choose unit</option>{nodes.filter(n=>n.kind==='unit').map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select><label htmlFor="library-name">Library entry name</label><input id="library-name" value={name} onChange={e=>setName(e.target.value)}/><button className="secondary" disabled={!editable||!unit||saving}>Save unit to library</button></form>
 <Notice {...result}/>{result.data&&<><ul className="collab-list">{result.data.items.map(entry=><li key={entry.id}><strong>{entry.name}</strong><button className="secondary" disabled={!editable||saving} onClick={()=>void act(()=>importUnit(revisionId,entry.id),'Unit imported with new graph IDs.')}>Import {entry.name}</button></li>)}</ul>{result.data.totalCount===0&&<p>No saved units in this workspace.</p>}<Pager offset={offset} total={result.data.totalCount} onChange={setOffset} label="units"/></>}
 <details><summary>Save an outcome/unit template</summary><p>This template preserves outcome and unit names and their memberships, not project phases or generated items. Use the unit library for a complete unit snapshot.</p><form className="collab-form" onSubmit={e=>{e.preventDefault();void act(()=>saveTemplate(workspaceId,code,templateName,templateSeed()),'Template saved. Reload the template chooser to use it.')}}><label htmlFor="save-template-name">Template name</label><input id="save-template-name" required value={templateName} onChange={e=>setTemplateName(e.target.value)}/><label htmlFor="save-template-code">Unique template code</label><input id="save-template-code" required value={code} onChange={e=>setCode(e.target.value)}/><button className="secondary" disabled={!editable||saving}>Save template</button></form></details>
 {message&&<p role="status">{message}</p>}</section>
}
export function Sharing({curriculumId,editable}:{curriculumId:string;editable:boolean}){
 const [offset,setOffset]=useState(0);const [target,setTarget]=useState('');const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
 const result=useRemote(signal=>shares(curriculumId,offset,signal),[curriculumId,offset]);
 async function act(action:()=>Promise<unknown>,question:string){if(!window.confirm(question))return;setSaving(true);setMessage('');try{await action();setMessage('Sharing updated.');result.reload()}catch(e){setMessage(problem(e))}finally{setSaving(false)}}
 return <section className="collab-section"><h3>Read-only sharing</h3><p>A grant permits plan reads only. It never grants authoring membership.</p><form className="collab-form" onSubmit={e=>{e.preventDefault();void act(()=>share(curriculumId,target),`Share this curriculum read-only with workspace ${target}?`)}}><label htmlFor="share-target">Target workspace ID (provided by its owner)</label><input id="share-target" required value={target} onChange={e=>setTarget(e.target.value)}/><button className="secondary" disabled={!editable||saving}>Grant read-only access</button></form><Notice {...result}/>{result.data&&<><ul className="collab-list">{result.data.items.map(grant=><li key={grant.targetWorkspaceId}><div><strong>{grant.targetWorkspaceName}</strong><small>{grant.targetWorkspaceId} · read only</small></div><button className="secondary" disabled={!editable||saving} onClick={()=>void act(()=>revoke(curriculumId,grant.targetWorkspaceId),`Revoke access for ${grant.targetWorkspaceName}?`)}>Revoke</button></li>)}</ul>{!result.data.totalCount&&<p>No outgoing grants.</p>}<Pager offset={offset} total={result.data.totalCount} onChange={setOffset} label="grants"/></>}{message&&<p role="status">{message}</p>}</section>
}
