package repo

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestLooksLikeTutorAuthored(t *testing.T) {
	t.Parallel()
	assert.False(t, looksLikeTutorAuthored("I wrote this myself about ls and cd."))
	assert.True(t, looksLikeTutorAuthored("As your tutor I recommend pwd."))
	assert.True(t, looksLikeTutorAuthored("hello [tutor] world"))
	assert.True(t, looksLikeTutorAuthored("I am an AI helper"))
	assert.True(t, looksLikeTutorAuthored("Generated by the tutor earlier"))
}
