-- +goose Up
-- +goose StatementBegin
ALTER TABLE stytch_mappings DROP CONSTRAINT stytch_mappings_account_id_fkey;
ALTER TABLE stytch_mappings ADD CONSTRAINT stytch_mappings_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT;
CREATE TABLE broker_transactions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), oauth_client_id uuid NOT NULL, redirect_id uuid NOT NULL, state_hash bytea NOT NULL, state_pepper_version smallint NOT NULL, state_sealed bytea NULL, state_key_version smallint NOT NULL, state_length smallint NOT NULL, provider_code_sealed bytea NULL, provider_code_key_version smallint NULL, pkce_challenge char(43) NOT NULL, pkce_method varchar(8) NOT NULL DEFAULT 'S256', requested_scopes text[] NOT NULL, resource_uri varchar(2048) NOT NULL, audience varchar(128) NOT NULL, broker_cookie_hash bytea NOT NULL, broker_cookie_pepper_version smallint NOT NULL, status varchar(24) NOT NULL DEFAULT 'pending', failure_code varchar(64) NULL, account_id uuid NULL, provider_session_association_id uuid NULL, created_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, provider_started_at timestamptz NULL, provider_validating_at timestamptz NULL, completed_at timestamptz NULL, version bigint NOT NULL DEFAULT 0,
 CONSTRAINT broker_transactions_oauth_client_fk FOREIGN KEY (oauth_client_id) REFERENCES oauth_clients(id) ON DELETE RESTRICT,
 CONSTRAINT broker_transactions_redirect_fk FOREIGN KEY (redirect_id) REFERENCES oauth_client_redirects(id) ON DELETE RESTRICT,
 CONSTRAINT broker_transactions_account_fk FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT,
 CONSTRAINT broker_transactions_state_hash_len CHECK (octet_length(state_hash)=32), CONSTRAINT broker_transactions_cookie_hash_len CHECK (octet_length(broker_cookie_hash)=32), CONSTRAINT broker_transactions_state_size CHECK (state_length BETWEEN 1 AND 1024 AND (state_sealed IS NULL OR octet_length(state_sealed) BETWEEN 30 AND 1053)), CONSTRAINT broker_transactions_state_versions CHECK (state_pepper_version > 0 AND state_key_version > 0), CONSTRAINT broker_transactions_provider_code_ck CHECK ((provider_code_sealed IS NULL) = (provider_code_key_version IS NULL)), CONSTRAINT broker_transactions_pkce_ck CHECK (pkce_method='S256' AND pkce_challenge ~ '^[A-Za-z0-9_-]{43}$'), CONSTRAINT broker_transactions_status CHECK (status IN ('pending','provider_started','provider_validating','authorized','denied','failed','expired')), CONSTRAINT broker_transactions_expiry CHECK (expires_at > created_at AND expires_at <= created_at + interval '10 minutes'), CONSTRAINT broker_transactions_terminal_erasure_ck CHECK ((status IN ('pending','provider_started','provider_validating') AND state_sealed IS NOT NULL) OR (status IN ('authorized','denied','failed','expired') AND state_sealed IS NULL AND provider_code_sealed IS NULL)), CONSTRAINT broker_transactions_human_account_assoc_xor_ck CHECK (((account_id IS NULL AND provider_session_association_id IS NULL) OR (account_id IS NOT NULL AND provider_session_association_id IS NOT NULL)) IS TRUE)
);
CREATE UNIQUE INDEX broker_transactions_active_state_uq ON broker_transactions(state_hash) WHERE status IN ('pending','provider_started','provider_validating'); CREATE UNIQUE INDEX broker_transactions_active_cookie_uq ON broker_transactions(broker_cookie_hash) WHERE status IN ('pending','provider_started','provider_validating'); CREATE INDEX broker_transactions_expiry_idx ON broker_transactions(expires_at);
CREATE TABLE provider_session_associations (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL, stytch_mapping_id uuid NOT NULL, provider varchar(32) NOT NULL DEFAULT 'stytch_b2b', provider_project_id varchar(255) NOT NULL, provider_organization_id varchar(255) NOT NULL, provider_member_id varchar(255) NOT NULL, provider_member_session_id varchar(255) NOT NULL, provider_expires_at timestamptz NOT NULL, status varchar(16) NOT NULL DEFAULT 'active', last_validated_at timestamptz NOT NULL, revoked_at timestamptz NULL, revoke_reason_code varchar(64) NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT provider_session_associations_account_fk FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT, CONSTRAINT provider_session_associations_stytch_mapping_fk FOREIGN KEY (stytch_mapping_id) REFERENCES stytch_mappings(id) ON DELETE RESTRICT, CONSTRAINT provider_session_associations_uq UNIQUE (provider,provider_project_id,provider_member_session_id), CONSTRAINT provider_session_associations_id_account_uq UNIQUE (id,account_id), CONSTRAINT provider_session_associations_status_ck CHECK (provider='stytch_b2b' AND status IN ('active','revoked','expired','suspended')), CONSTRAINT provider_session_associations_ids_ck CHECK (provider_project_id !~ '[[:cntrl:]]' AND provider_organization_id !~ '[[:cntrl:]]' AND provider_member_id !~ '[[:cntrl:]]' AND provider_member_session_id !~ '[[:cntrl:]]'), CONSTRAINT provider_session_associations_terminal_ck CHECK ((status='active' AND revoked_at IS NULL AND revoke_reason_code IS NULL) OR (status<>'active' AND revoked_at IS NOT NULL AND revoke_reason_code IS NOT NULL))
);
CREATE INDEX provider_session_associations_tuple_idx ON provider_session_associations(provider,provider_project_id,provider_organization_id,provider_member_id);
CREATE OR REPLACE FUNCTION identity_association_mapping_tuple() RETURNS trigger AS $$ DECLARE mapping stytch_mappings%ROWTYPE; BEGIN SELECT * INTO mapping FROM stytch_mappings WHERE id=NEW.stytch_mapping_id FOR KEY SHARE; IF NOT FOUND OR mapping.account_id<>NEW.account_id OR mapping.project_id<>NEW.provider_project_id OR mapping.organization_id<>NEW.provider_organization_id OR mapping.member_id<>NEW.provider_member_id THEN RAISE EXCEPTION 'association mapping tuple mismatch'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE CONSTRAINT TRIGGER provider_session_associations_stytch_mapping_tuple_ck AFTER INSERT OR UPDATE ON provider_session_associations DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION identity_association_mapping_tuple();
ALTER TABLE broker_transactions ADD CONSTRAINT broker_transactions_association_fk FOREIGN KEY (provider_session_association_id) REFERENCES provider_session_associations(id) ON DELETE RESTRICT; ALTER TABLE broker_transactions ADD CONSTRAINT broker_transactions_association_account_fk FOREIGN KEY (provider_session_association_id,account_id) REFERENCES provider_session_associations(id,account_id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE oauth_grants (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NULL, service_principal_id uuid NULL, oauth_client_id uuid NOT NULL, provider_session_association_id uuid NULL, resource_uri varchar(2048) NOT NULL, audience varchar(128) NOT NULL, scopes text[] NOT NULL, subject_class varchar(16) NOT NULL, status varchar(16) NOT NULL DEFAULT 'active', granted_at timestamptz NOT NULL DEFAULT now(), not_after timestamptz NOT NULL, revoked_at timestamptz NULL, revoke_reason_code varchar(64) NULL, version bigint NOT NULL DEFAULT 0,
 CONSTRAINT oauth_grants_account_fk FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT, CONSTRAINT oauth_grants_oauth_client_fk FOREIGN KEY (oauth_client_id) REFERENCES oauth_clients(id) ON DELETE RESTRICT, CONSTRAINT oauth_grants_association_fk FOREIGN KEY (provider_session_association_id) REFERENCES provider_session_associations(id) ON DELETE RESTRICT, CONSTRAINT oauth_grants_class_status_ck CHECK (subject_class IN ('human','service') AND status IN ('active','revoked','expired')), CONSTRAINT oauth_grants_subject_xor_ck CHECK (((subject_class='human' AND account_id IS NOT NULL AND service_principal_id IS NULL AND provider_session_association_id IS NOT NULL) OR (subject_class='service' AND account_id IS NULL AND service_principal_id IS NOT NULL AND provider_session_association_id IS NULL)) IS TRUE), CONSTRAINT oauth_grants_lifetime_ck CHECK (not_after>granted_at), CONSTRAINT oauth_grants_terminal_ck CHECK ((status='active' AND revoked_at IS NULL AND revoke_reason_code IS NULL) OR (status<>'active' AND revoked_at IS NOT NULL AND revoke_reason_code IS NOT NULL))
);
CREATE UNIQUE INDEX oauth_grants_active_human_uq ON oauth_grants(account_id,oauth_client_id,provider_session_association_id,resource_uri,audience) WHERE subject_class='human' AND status='active'; -- Safe before IB5; it needs no future FK.
CREATE UNIQUE INDEX oauth_grants_active_service_uq ON oauth_grants(service_principal_id,oauth_client_id,resource_uri,audience) WHERE subject_class='service' AND status='active';
ALTER TABLE oauth_grants ADD CONSTRAINT oauth_grants_association_account_fk FOREIGN KEY (provider_session_association_id,account_id) REFERENCES provider_session_associations(id,account_id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE oauth_authorization_codes (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), code_hash bytea NOT NULL, pepper_version smallint NOT NULL, grant_id uuid NOT NULL, broker_transaction_id uuid NOT NULL, oauth_client_id uuid NOT NULL, redirect_uri varchar(2048) NOT NULL, resource_uri varchar(2048) NOT NULL, audience varchar(128) NOT NULL, scopes text[] NOT NULL, pkce_challenge char(43) NOT NULL, pkce_method varchar(8) NOT NULL DEFAULT 'S256', issued_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL, consumed_at timestamptz NULL,
 CONSTRAINT oauth_authorization_codes_grant_fk FOREIGN KEY (grant_id) REFERENCES oauth_grants(id) ON DELETE RESTRICT, CONSTRAINT oauth_authorization_codes_broker_fk FOREIGN KEY (broker_transaction_id) REFERENCES broker_transactions(id) ON DELETE RESTRICT, CONSTRAINT oauth_authorization_codes_oauth_client_fk FOREIGN KEY (oauth_client_id) REFERENCES oauth_clients(id) ON DELETE RESTRICT, CONSTRAINT oauth_authorization_codes_hash_lifetime_ck CHECK (octet_length(code_hash)=32 AND pepper_version>0 AND expires_at>issued_at AND expires_at<=issued_at+interval '60 seconds'), CONSTRAINT oauth_authorization_codes_pkce_ck CHECK (pkce_method='S256' AND pkce_challenge ~ '^[A-Za-z0-9_-]{43}$'), CONSTRAINT oauth_authorization_codes_hash_uq UNIQUE(code_hash), CONSTRAINT oauth_authorization_codes_broker_uq UNIQUE(broker_transaction_id)
);
CREATE CONSTRAINT TRIGGER oauth_grants_scopes_canonical_ck AFTER INSERT OR UPDATE OF scopes ON oauth_grants DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION identity_canonical_text_array(); CREATE CONSTRAINT TRIGGER oauth_authorization_codes_scopes_canonical_ck AFTER INSERT OR UPDATE OF scopes ON oauth_authorization_codes DEFERRABLE INITIALLY IMMEDIATE FOR EACH ROW EXECUTE FUNCTION identity_canonical_text_array();
-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS oauth_authorization_codes; DROP TABLE IF EXISTS oauth_grants; DROP TABLE IF EXISTS broker_transactions; DROP TABLE IF EXISTS provider_session_associations; DROP FUNCTION IF EXISTS identity_association_mapping_tuple(); ALTER TABLE stytch_mappings DROP CONSTRAINT IF EXISTS stytch_mappings_account_id_fkey; ALTER TABLE stytch_mappings ADD CONSTRAINT stytch_mappings_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;
-- +goose StatementEnd
